coverage:
  precision: 1
  round: nearest
  status:
    project:
      default:
        target: auto
        threshold: 2% # Allow coverage to drop slightly
        removed_code_behavior: adjust_base
    patch:
      default:
        target: auto
        threshold: 5% # Allow coverage to drop slightly
        removed_code_behavior: adjust_base

comment:
  layout: header, components, diff, files, footer
  behavior: new

component_management:
  individual_components:
    - component_id: parser
      name: Parser
      paths:
        - src/parser/**
    - component_id: ir
      name: Intermediate Representation
      paths:
        - src/ir/**
    - component_id: synthesizer
      name: Synthesizers
      paths:
        - src/synthesizer/**
    - component_id: other
      name: Other
      paths:
        - src/errors/**
        - src/primitives/**
        - src/specification/**
        - src/*.rs
