version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    labels: 
    - auto-approve
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    labels: 
    - auto-approve
    schedule:
      interval: daily
