# autogenerated
import aws_cdk as cdk
from stack import VpcStack
app = cdk.App(
    default_stack_synthesizer=cdk.DefaultStackSynthesizer(
        generate_bootstrap_version_rule=False
        )
    )

VpcStack(app, 'Stack')
app.synth()
