# autogenerated
import aws_cdk as cdk
from stack import Ec2Stack
app = cdk.App(
    default_stack_synthesizer=cdk.DefaultStackSynthesizer(
        generate_bootstrap_version_rule=False
        )
    )

Ec2Stack(app, 'Stack')
app.synth()
