on:
  push:
    branches: [main]
  pull_request: {}
name: Checks

jobs:
  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      # Ensure build.rs has ran before we assert formatting...
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./Cargo.toml --all -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./Cargo.toml -- -Adead-code -D warnings

  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Tests with Coverage
        run: bash tasks/coverage.sh
      - name: Upload CodeCov artifact
        uses: actions/upload-artifact@v3
        with:
          name: codecov.json
          path: target/codecov.json
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/coverage/html

  upload:
    name: Submit Coverage to CodeCov
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: Download CodeCov artifact
        uses: actions/download-artifact@v3
        with:
          name: codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: codecov.json
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
