name: security-audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: rustsec/audit-check@main
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
