name: security-audit
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
