name: 'update-schema'

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  schema:
    name: 'Schema'

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.1.0'

      - name: 'Download schema'
        run: 'wget --output-document=src/specification/spec.json.gz https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json'

      - name: 'Unzip spec'
        run: 'gunzip -f src/specification/spec.json.gz'

      - name: 'Sort json'
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'cat src/specification/spec.json | jq --sort-keys >> src/specification/spec_sorted.json'

      - name: 'Move to spec'
        run: 'mv src/specification/spec_sorted.json src/specification/spec.json'

      - name: 'Set git identity'
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 'Build package'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: 'Show diff'
        run: 'git diff'

      - name: 'Open pull request updating schema'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          author: github-actions <github-actions@github.com>
          committer: github-actions <github-actions@github.com>
          signoff: true
          branch: github-actions/update-schema
          body: |
            Updates CloudFormation Specification. See details in [workflow run].

            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          commit-message: |-
            chore: upgrade cloudformation specification

            Updates CloudFormation Specification. See details in [workflow run].

            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          title: 'chore: update cloudformation specification'
          labels: auto-approve
